name: deployment

on:
  push:
    branches:
      - main
    paths:
      - deploy/**/*
      - src/**/*
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  ECR_REPOSITORY: api
  VPC_ID: vpc-052ef000932e819c2

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_url: ${{ steps.build-image.outputs.image_url }}
      account_id: ${{ steps.credentials.outputs.aws-account-id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./deploy/package-lock.json

      - name: Install Node Dependencies
        working-directory: ./deploy
        run: npm clean-install

      - name: Install Dependencies
        working-directory: ./src
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Configure AWS credentials
        id: credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        # A unique identifier assigned to a specific step within a job in a workflow. 
        # It is used to reference the output of that step in subsequent steps, 
        # allowing for better organization and control of the workflow's execution.
        # We use this later to get the registry URL.
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          export image_url="${ECR_REGISTRY}/${ECR_REPOSITORY}:$(date '+%Y%m%d-%H%M%S')"
          docker build -t $image_url .
          docker push $image_url
          echo "image_url=${image_url}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./deploy/package-lock.json

      - name: Install Node Dependencies
        working-directory: ./deploy
        run: npm ci

      - name: Configure AWS credentials
        id: credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true
          mask-aws-account-id: false

      - name: Deploy using CDK
        working-directory: ./deploy
        env:
          IMAGE_URL: ${{needs.build.outputs.image_url}}
          ACCOUNT_ID: ${{needs.build.outputs.account_id}}
        run: |
          echo $IMAGE_URL
          npx cdk deploy --require-approval=never
